### ISSUE TITLE
Error: No such property: scriptPrefix

### ISSUE THREAD

**Issue by shawnli88** [qooxdoo/qxl.demobrowser#2]
qx serve
show these error.

            async.eachSeries(appInfos,
              (appInfo, cb) => {
                target.set({
                  scriptPrefix: appInfo.className + "-"
                });
                // Calculate dependencies and write it out

PS E:\tmp\ootest\msw\test5d\test5\qx_packages\qooxdoo_qxl_demobrowser_master> qx serve
Making applications...
>>> Making the applications...
Cannot find asset alias referenced in qxl.demobrowser:qxl/demobrowser/demo/fonts/fontawesome-webfont.meta
Cannot find asset mapping referenced in qxl.demobrowser:qxl/demobrowser/demo/fonts/fontawesome-webfont.meta
Cannot find asset size referenced in qxl.demobrowser:qxl/demobrowser/demo/fonts/fontawesome-webfont.meta
Writing application demobrowser

DEMO BUILD STARTED
Catch entries in E:/tmp/ootest/msw/test5d/test5/qx_packages/qooxdoo_qxl_demobrowser_master/source/demo/
246 entries (files and directories) catched
compiled/source/demobrowser/script/demodata.json created

get apps
no class found for bom/blank.html
no class found for widget/blank.html
DEMO BUILD START COMPILE
C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\@qooxdoo\framework\lib\qx_server\part-0.js:22282
              throw new Error("No such property: " + prop);
              ^

**Error: No such property: scriptPrefix**
    at wrapper.set (C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\@qooxdoo\framework\lib\qx_server\part-0.js:22282:21)
    at async.eachSeries **(E:\tmp\ootest\msw\test5d\test5\qx_packages\qooxdoo_qxl_demobrowser_master\compile.js:119:24)**
    at C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:3110:16
    at replenish (C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:1011:17)
    at C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:1016:9
    at eachLimit$1 (C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:3196:24)
    at Object.<anonymous> (C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:1046:16)
    at async.series (E:\tmp\ootest\msw\test5d\test5\qx_packages\qooxdoo_qxl_demobrowser_master\compile.js:117:19)
    at C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:3880:24
    at replenish (C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:1011:17)
    at iterateeCallback (C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:995:17)
    at C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:969:16
    at C:\Users\lixm\AppData\Roaming\npm\node_modules\@qooxdoo\compiler\node_modules\async\dist\async.js:3885:13
    at E:\tmp\ootest\msw\test5d\test5\qx_packages\qooxdoo_qxl_demobrowser_master\tool\lib\DataGenerator.js:346:19
    at WriteStream.<anonymous> (E:\tmp\ootest\msw\test5d\test5\qx_packages\qooxdoo_qxl_demobrowser_master\tool\lib\DataGenerator.js:381:9)
    at WriteStream.emit (events.js:198:13)

**Comment by cboulanger** [comment]
I can reproduce the bug.
